spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lms_system
    username: root
    password: '*seoksm1017*'
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


mail:
  host: smtp.gmail.com
  port: 587
  username: seoksmin@gmail.com
  password: ykgwjrctzyvdymax
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    root: debug

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
